# Generated by Django 3.2.5 on 2022-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('postDate', models.DateTimeField(max_length=40)),
                ('thumbnail', models.ImageField(default='', null=True, upload_to='blog/thumnail/')),
            ],
        ),
    ]
