# Generated by Django 3.2.5 on 2022-02-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='myPost',
        ),
    ]
