# Generated by Django 3.2.5 on 2022-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_rename_post_mypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='postDate',
            field=models.DateField(max_length=40),
        ),
    ]
