# Generated by Django 3.2.5 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='postViews',
            field=models.IntegerField(default=0),
        ),
    ]
