# Generated by Django 3.2.5 on 2022-02-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0007_mypost_postviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='thumbnail',
        ),
    ]
